import { LucideSparkles } from "lucide-react";

import { Badge } from "@/components/ui/badge";

interface AnalysisOverviewProps {
  summary: string;
}

export function AnalysisOverview({ summary }: AnalysisOverviewProps) {
  return (
    <section className="p-4 col-start-1 lg:col-start-auto">
      <header className="pb-2">
        <h2 id="overview-heading" className="font-semibold text-lg">
          Overview
          <Badge
            variant="outline"
            className="ml-2"
            aria-label="Content generated by artificial intelligence"
            title="This overview was generated using AI analysis"
          >
            <LucideSparkles className="w-3 h-3 mr-1" aria-hidden="true" />
            <span>AI Generated</span>
          </Badge>
        </h2>
      </header>
      <div className="overview-content">
        <p
          className="text-muted-foreground text-sm"
          aria-describedby="overview-heading"
        >
          {summary}
        </p>
      </div>
    </section>
  );
}
